import {
  AZ,
  ATL,
  BAL,
  BUF,
  CAR,
  CHI,
  CIN,
  CLE,
  DAL,
  DEN,
  DET,
  GB,
  HOU,
  IND,
  JAC,
  KC,
  LAC,
  LAR,
  MIA,
  MIN,
  NE,
  NO,
  NYG,
  NYJ,
  OAK,
  PHI,
  PIT,
  SF,
  SEA,
  TB,
  TEN,
  WAS,
} from './logos';

interface TeamProps {
  name: string;
  abbreviation: string;
  logo: string;
  textColor: '#FFF' | '#000';
  primaryColor: string;
  secondaryColor: string;
  accentColor: string;
  secondaryAccentColor?: string;
}

export const teams: TeamProps[] = [
  {
    name: 'arizona cardinals',
    abbreviation: 'AZ',
    logo: AZ,
    textColor: '#000',
    primaryColor: '#97233F',
    secondaryColor: '#000000',
    accentColor: '#FFB612',
  },
  {
    name: 'atlanta falcons',
    abbreviation: 'ATL',
    logo: ATL,
    textColor: '#000',
    primaryColor: '#A71930',
    secondaryColor: '#000000',
    accentColor: '#A5ACAF',
  },
  {
    name: 'baltimore ravens',
    abbreviation: 'BAL',
    logo: BAL,
    textColor: '#FFF',
    primaryColor: '#241773',
    secondaryColor: '#000000',
    accentColor: '#9E7C0C',
    secondaryAccentColor: '#C60C30',
  },
  {
    name: 'buffalo bills',
    abbreviation: 'BUF',
    logo: BUF,
    textColor: '#FFF',
    primaryColor: '#00338D',
    secondaryColor: '#C60C30',
    accentColor: '#FFFFFF',
  },
  {
    name: 'carolina panthers',
    abbreviation: 'CAR',
    logo: CAR,
    textColor: '#000',
    primaryColor: '#0085CA',
    secondaryColor: '#101820',
    accentColor: '#BFC0BF',
  },
  {
    name: 'chicago bears',
    abbreviation: 'CHI',
    logo: CHI,
    textColor: '#FFF',
    primaryColor: '#0B162A',
    secondaryColor: '#C83803',
    accentColor: '#FFFFFF',
  },
  {
    name: 'cincinatti bengals',
    abbreviation: 'CIN',
    logo: CIN,
    textColor: '#000',
    primaryColor: '#FB4F14',
    secondaryColor: '#000000',
    accentColor: '#FFFFFF',
  },
  {
    name: 'cleveland browns',
    abbreviation: 'CLE',
    logo: CLE,
    textColor: '#FFF',
    primaryColor: '#311D00',
    secondaryColor: '#FF3C00',
    accentColor: '#FFFFFF',
  },
  {
    name: 'dallas cowboys',
    abbreviation: 'DAL',
    logo: DAL,
    textColor: '#FFF',
    primaryColor: '#041E42',
    secondaryColor: '#FFFFFF',
    accentColor: '#003594',
  },
  {
    name: 'denver broncos',
    abbreviation: 'DEN',
    logo: DEN,
    textColor: '#FFF',
    primaryColor: '#FB4F14',
    secondaryColor: '#002244',
    accentColor: '#FFFFFF',
  },
  {
    name: 'detroit lions',
    abbreviation: 'DET',
    logo: DET,
    textColor: '#FFF',
    primaryColor: '#0076B6',
    secondaryColor: '#B0B7BC',
    accentColor: '#FFFFFF',
  },
  {
    name: 'green bay packers',
    abbreviation: 'GB',
    logo: GB,
    textColor: '#FFF',
    primaryColor: '#203731',
    secondaryColor: '#FFB612',
    accentColor: '#FFFFFF',
  },
  {
    name: 'houston texans',
    abbreviation: 'HOU',
    logo: HOU,
    textColor: '#FFF',
    primaryColor: '#03202F',
    secondaryColor: '#A71930',
    accentColor: '#FFFFFF',
  },
  {
    name: 'indianapolis colts',
    abbreviation: 'IND',
    logo: IND,
    textColor: '#FFF',
    primaryColor: '#002C5F',
    secondaryColor: '#A2AAAD',
    accentColor: '#FFFFFF',
  },
  {
    name: 'jacksonville jaguars',
    abbreviation: 'JAC',
    logo: JAC,
    textColor: '#FFF',
    primaryColor: '#006778',
    secondaryColor: '#D7A22A',
    accentColor: '#101820',
  },
  {
    name: 'kansas city chiefs',
    abbreviation: 'KC',
    logo: KC,
    textColor: '#000',
    primaryColor: '#E31837',
    secondaryColor: '#FFB81C',
    accentColor: '#FFFFFF',
  },
  {
    name: 'los angeles chargers',
    abbreviation: 'LAC',
    logo: LAC,
    textColor: '#FFF',
    primaryColor: '#0080C6',
    secondaryColor: '#FFC20E',
    accentColor: '#002A5E',
  },
  {
    name: 'los angeles rams',
    abbreviation: 'LAR',
    logo: LAR,
    textColor: '#FFF',
    primaryColor: '#002244',
    secondaryColor: '#FFFFFF',
    accentColor: '#866D4B',
  },
  {
    name: 'miami dolphins',
    abbreviation: 'MIA',
    logo: MIA,
    textColor: '#FFF',
    primaryColor: '#008E97',
    secondaryColor: '#FC4C02',
    accentColor: '#005778',
  },
  {
    name: 'minnesota vikings',
    abbreviation: 'MIN',
    logo: MIN,
    textColor: '#FFF',
    primaryColor: '#4F2683',
    secondaryColor: '#FFC62F',
    accentColor: '#000000',
  },
  {
    name: 'new england patriots',
    abbreviation: 'NE',
    logo: NE,
    textColor: '#FFF',
    primaryColor: '#002244',
    secondaryColor: '#C60C30',
    accentColor: '#B0B7BC',
  },
  {
    name: 'new orleans saints',
    abbreviation: 'NO',
    logo: NO,
    textColor: '#000',
    primaryColor: '#D3BC8D',
    secondaryColor: '#101820',
    accentColor: '#FFFFFF',
  },
  {
    name: 'new york giants',
    abbreviation: 'NYG',
    logo: NYG,
    textColor: '#FFF',
    primaryColor: '#0B2265',
    secondaryColor: '#A71930',
    accentColor: '#A5ACAF',
  },
  {
    name: 'new york jets',
    abbreviation: 'NYJ',
    logo: NYJ,
    textColor: '#FFF',
    primaryColor: '#125740',
    secondaryColor: '#FFFFFF',
    accentColor: '#000000',
  },
  {
    name: 'oakland raiders',
    abbreviation: 'OAK',
    logo: OAK,
    textColor: '#FFF',
    primaryColor: '#000000',
    secondaryColor: '#A5ACAF',
    accentColor: '#FFFFFF',
  },
  {
    name: 'philiadelphia eagles',
    abbreviation: 'PHI',
    logo: PHI,
    textColor: '#FFF',
    primaryColor: '#004C54',
    secondaryColor: '#A5ACAF',
    accentColor: '#000000',
  },
  {
    name: 'pittsburgh steelers',
    abbreviation: 'PIT',
    logo: PIT,
    textColor: '#FFF',
    primaryColor: '#101820',
    secondaryColor: '#FFB612',
    accentColor: '#C60C30',
    secondaryAccentColor: '#003087',
  },
  {
    name: 'san fransico 49ers',
    abbreviation: 'SF',
    logo: SF,
    textColor: '#FFF',
    primaryColor: '#AA0000',
    secondaryColor: '#B3995D',
    accentColor: '#FFFFFF',
  },
  {
    name: 'seattle seahawks',
    abbreviation: 'SEA',
    logo: SEA,
    textColor: '#FFF',
    primaryColor: '#002244',
    secondaryColor: '#69BE28',
    accentColor: '#A5ACAF',
  },
  {
    name: 'tampa bay buccaneers',
    abbreviation: 'TB',
    logo: TB,
    textColor: '#FFF',
    primaryColor: '#D50A0A',
    secondaryColor: '#34302B',
    accentColor: '#FF7900',
  },
  {
    name: 'tennessee titans',
    abbreviation: 'TEN',
    logo: TEN,
    textColor: '#FFF',
    primaryColor: '#0C2340',
    secondaryColor: '#418FDE',
    accentColor: '#C8102E',
  },
  {
    name: 'washington redskins',
    abbreviation: 'WAS',
    logo: WAS,
    textColor: '#FFF',
    primaryColor: '#773141',
    secondaryColor: '#FFB612',
    accentColor: '#FFFFFF',
  },
];
